
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meta_sys?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      firstName: Demo
  filter:
    create: All tasks