
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9987
  servlet:
    # 应用的访问路径
    context-path: /meta-app
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meta_sys?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

camunda:
  bpm:
    admin-user:
      id: transduck
      password: 111111