
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9987
  servlet:
    # 应用的访问路径
    context-path: /meta-app
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

mybatis-flex:
  global-config:
    print-banner: false
  configuration:
    mapUnderscoreToCamelCase: true
    safeRowBoundsEnabled: true
  datasource:
    talent_rw:
      url: jdbc:mysql://localhost:3306/test_demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&connectTimeout=1000&socketTimeout=30000
      username: root
      password: root
      type: druid
      minIdle: 10
      maxActive: 100
      maxWait: 1000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: -1
      filters: stat
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=20000
      useGlobalDataSourceStat: true