spring:
  application:
    name: spring-boot-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/sakila?serverTimezone=UTC
    username: 'root'
    password: 'root'

