version: '3.8'

networks:
  1panel-network:
    external: true

services:
  kibana:
    container_name: kibana8
    image: kibana:8.15.3
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch
      - ELASTICSEARCH_USERNAME=kibana_user
      - ELASTICSEARCH_PASSWORD=Kibana_User_Pass
      - XPACK_SECURITY_ENABLED=true
      - TZ=Asia/Shanghai
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5601
      - SERVER_SSL_ENABLED=false
    labels:
      createdBy: Apps
    networks:
      - 1panel-network
    ports:
      - "5601:5601"
    restart: always
