version: "3"

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6.3'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=Asia/Shanghai
      - audit.enable=true
    privileged: true
#    command: /bin/bash -c "/opt/bitnami/zookeeper/bin/zkServer.sh config/zookeeper.properties"
    volumes:
      - "./data/apps/kafka/zookeeper_data:/bitnami"
      - "./data/apps/kafka/zookeeper_data/conf:/bitnami/zookeeper/conf"
    networks:
      kafka:
        aliases:
          - zookeeper

  kafka:
    image: 'bitnami/kafka:3.2.3'
    container_name: kafka
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_PROCESS_ROLES=BROKER,CONTROLLER
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092  #传递回客户端的元数据，填写宿主机IP地址
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    privileged: true
    depends_on:
      - zookeeper
    volumes:
      - "./data/apps/kafka/kafka_data:/bitnami"
    networks:
      kafka:
        aliases:
          - kafka

#  kafka-client:
#    image: 'bitnami/kafka:3.2.3'
#    container_name: kafka-client
#    ports:
#      - '9094:9092'
#      - '9095:9093'
#    environment:
#      - TZ=Asia/Shanghai
#      - KAFKA_ENABLE_KRAFT=yes
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_PROCESS_ROLES=broker
#      - KAFKA_CFG_LISTENERS=CLIENT://:9094,EXTERNAL://:9095
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
#      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9094,EXTERNAL://localhost:9095
#      - KAFKA_BROKER_ID=1
#      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9095
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    privileged: true
#    depends_on:
#      - zookeeper
#    volumes:
#      - "./data/apps/kafka/kafka_data_client:/bitnami"
#    networks:
#      kafka:
#        aliases:
#          - kafka-client






  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
#    restart: always
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_READONLY=true
    depends_on:
      - kafka
      - zookeeper
    privileged: true
    networks:
      kafka:
        aliases:
          - kafka-ui


networks:
  kafka:
    driver: bridge