spring:
  data:
    mongodb:
      host: 10.0.203.172
      port: 27017
      database: sse_test
      username: mongo_ED8xkp
      password: mongo_x7Cd4k
sse:
  msg:
    send:
      group:
        url: http://10.10.3.29:8080/msg/group
        id: 65