server:
  port: 8899
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: sse-server
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
logging:
  config: classpath:logback-spring.xml
  level:
    com.java: info
    org.springframework.data.mongodb: DEBUG
    com.mongodb: DEBUG