-- test_demo.douyin_blogger_info definition

CREATE TABLE `douyin_blogger_info` (
                                       `id` bigint NOT NULL AUTO_INCREMENT,
                                       `blogger_id` varchar(50) NOT NULL COMMENT '博主ID',
                                       `blogger_name` varchar(100) NOT NULL COMMENT '博主名称',
                                       `blogger_avatar` varchar(255) DEFAULT NULL COMMENT '博主头像',
                                       `gender` tinyint(1) DEFAULT NULL COMMENT '性别（1：男，2：女）',
                                       `age` tinyint DEFAULT NULL COMMENT '年龄',
                                       `province` varchar(50) DEFAULT NULL COMMENT '省份',
                                       `city` varchar(50) DEFAULT NULL COMMENT '城市',
                                       `birthday` date DEFAULT NULL COMMENT '生日',
                                       `constellation` varchar(50) DEFAULT NULL COMMENT '星座',
                                       `industry` varchar(50) DEFAULT NULL COMMENT '行业',
                                       `label` varchar(255) DEFAULT NULL COMMENT '标签',
                                       `follower_count` int DEFAULT '0' COMMENT '粉丝数',
                                       `following_count` int DEFAULT '0' COMMENT '关注数',
                                       `total_likes` int DEFAULT '0' COMMENT '获赞总数',
                                       `total_comments` int DEFAULT '0' COMMENT '评论总数',
                                       `total_shares` int DEFAULT '0' COMMENT '分享总数',
                                       `total_videos` int DEFAULT '0' COMMENT '视频总数',
                                       `average_views` int DEFAULT '0' COMMENT '平均播放量',
                                       `average_likes` int DEFAULT '0' COMMENT '平均点赞数',
                                       `average_comments` int DEFAULT '0' COMMENT '平均评论数',
                                       `average_shares` int DEFAULT '0' COMMENT '平均分享数',
                                       `video_gmv_30d` decimal(10,2) DEFAULT '0.00' COMMENT '近30天视频GMV',
                                       `video_gmv_90d` decimal(10,2) DEFAULT '0.00' COMMENT '近90天视频GMV',
                                       `video_gmv_180d` decimal(10,2) DEFAULT '0.00' COMMENT '近180天视频GMV',
                                       `video_gmv_365d` decimal(10,2) DEFAULT '0.00' COMMENT '近365天视频GMV',
                                       `total_gmv` decimal(10,2) DEFAULT '0.00' COMMENT '累计视频GMV',
                                       `last_video_upload_time` datetime DEFAULT NULL COMMENT '最后发布视频时间',
                                       `last_active_time` datetime DEFAULT NULL COMMENT '最后活跃时间',
                                       `account_create_time` datetime DEFAULT NULL COMMENT '账号创建时间',
                                       `verified` tinyint(1) DEFAULT '0' COMMENT '是否认证（1：是，0：否）',
                                       `platform` varchar(50) DEFAULT 'douyin' COMMENT '平台（默认：抖音）',
                                       `blogger_type` varchar(50) DEFAULT NULL COMMENT '博主类型',
                                       `blogger_level` tinyint DEFAULT '0' COMMENT '博主等级',
                                       `cooperation_status` tinyint(1) DEFAULT '0' COMMENT '合作状态（1：已合作，0：未合作）',
                                       `channel_id` varchar(50) DEFAULT NULL COMMENT '频道ID',
                                       `channel_name` varchar(100) DEFAULT NULL COMMENT '频道名称',
                                       `channel_avatar` varchar(255) DEFAULT NULL COMMENT '频道头像',
                                       `channel_follower_count` int DEFAULT '0' COMMENT '频道粉丝数',
                                       `channel_total_videos` int DEFAULT '0' COMMENT '频道视频总数',
                                       `channel_total_likes` int DEFAULT '0' COMMENT '频道获赞总数',
                                       `channel_total_comments` int DEFAULT '0' COMMENT '频道评论总数',
                                       `channel_total_shares` int DEFAULT '0' COMMENT '频道分享总数',
                                       `channel_video_gmv_30d` decimal(10,2) DEFAULT '0.00' COMMENT '近30天频道GMV',
                                       `channel_video_gmv_90d` decimal(10,2) DEFAULT '0.00' COMMENT '近90天频道GMV',
                                       `channel_video_gmv_180d` decimal(10,2) DEFAULT '0.00' COMMENT '近180天频道GMV',
                                       `channel_video_gmv_365d` decimal(10,2) DEFAULT '0.00' COMMENT '近365天频道GMV',
                                       `channel_total_gmv` decimal(10,2) DEFAULT '0.00' COMMENT '累计频道GMV',
                                       `channel_last_video_upload_time` datetime DEFAULT NULL COMMENT '最后发布频道视频时间',
                                       `channel_last_active_time` datetime DEFAULT NULL COMMENT '最后活跃时间',
                                       `channel_account_create_time` datetime DEFAULT NULL COMMENT '频道创建时间',
                                       `channel_verified` tinyint(1) DEFAULT '0' COMMENT '频道是否认证',
                                       `del_flag` int DEFAULT '0' COMMENT '删除标志（0代表存在 2代表删除）',
                                       `create_by` bigint NOT NULL DEFAULT '0' COMMENT '创建者',
                                       `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                       `update_by` bigint NOT NULL DEFAULT '0' COMMENT '更新者',
                                       `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                                       `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '备注',
                                       PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=82 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;