server:
    port: 8090
spring:
    application:
        name: spring-boot-transactional
    datasource:
        data: classpath:data.sql
        driver-class-name: org.h2.Driver
        password:
        schema: classpath:schema.sql
        url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: san
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                use_sql_comments: true
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: true
                web-allow-others: true
