spring:
  data:
    mongodb:
      host: localhost
      port: 8999
      database: MGdatabase
#  datasource:
#    url: jdbc:mysql://localhost:3306/meta_sys?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080