version: "3"

services:
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
    environment:
      - ZOO_MY_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=Asia/Shanghai
      - ZOO_SERVER_ID=1
      - ZOO_LISTEN_ALLIPS_ENABLED=TRUE
    privileged: true
    volumes:
      - "./data/apps/kafka/zookeeper_data:/data"
    networks:
      kafka:
        aliases:
          - zookeeper

  kafka:
    image: 'wurstmeister/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.4:9092 # 传递回客户端的元数据，填写宿主机IP地址
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CREATE_TOPICS=Topic1:1:3,Topic2:1:1:compact
    privileged: true
    depends_on:
      - zookeeper
    volumes:
      - "./data/apps/kafka/kafka_data:/kafka"
    networks:
      kafka:
        aliases:
          - kafka

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    #    restart: always
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_READONLY=true
    depends_on:
      - kafka
      - zookeeper
    privileged: true
    networks:
      kafka:
        aliases:
          - kafka-ui


networks:
  kafka:
    driver: bridge