# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9987
  servlet:
    # 应用的访问路径
    context-path: /meta-app
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #minio配置
  minio:
    access-key: RQHKtS38Ji6XpEObO9iR
    secret-key: iHU6l0bonMOQxFzsLDwttgAJ6n77FEMUfff64JRY
    url: http://10.0.201.34:9000/
    bucket-name: wdhcr
