services:
  drawdb:
    image: xinsodev/drawdb
    container_name: some-drawdb
    ports:
      - "3000:80"
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      - 1panel-network


networks:
  1panel-network:
    external: true