server:
  port: 8080
spring:
  application:
    name: spring-boot-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: '***'
    url: jdbc:mysql://localhost:3306/database?serverTimezone=UTC
    username: '***'
