spring:
  datasource:
     url: jdbc:mysql://localhost:3306/spring_batch?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=Asia/Shanghai
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: root
     password: root

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
#      schema: org/springframework/batch/core/schema-mysql.sql
  devtools:
    restart:
      enabled: false
