server:
  # 服务器的HTTP端口，默认为8080
  port: 9888
  servlet:
    # 应用的访问路径
    context-path: /mp-dy
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100


spring:
  datasource:
    dynamic:
      primary: postgresql
      strict: true
      datasource:
        mysql:
          url: jdbc:mysql://localhost:3306/spring_boot_test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
        postgresql:
          url: postgresql://localhost:5432/postgres
          driver-class-name: org.postgresql.Driver
          username: postgres
          password: root


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
